import { Orbitron } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import FooterMenu from "./component/FooterMenu";

const Orbit = Orbitron({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Orbit.className}>
        <Navbar/>
        <main className="min-h-[65vh]">
          {children}
        </main>
        <Footer/>
        <FooterMenu/>
       
        </body>
    </html>
  );
}
